#!/command/with-contenv bash
# mlat-client configuration file
# This is a POSIX shell fragment.
# You can edit this file directly, or use
# "dpkg-reconfigure mlat-client"

# shellcheck shell=bash disable=SC1091,SC2076,SC2154

source /scripts/common

if ! chk_enabled "$MLAT"; then
  "${s6wrap[@]}" echo "MLAT is disabled, not starting mlat-client-sdrmap"
  sleep infinity
fi

# get the username from $SMUSERNAME. If SMUSERNAME is unset OR yourusername is the value, set USERNAME to blank

if [[ -z "$SMUSERNAME" ]] || [[ "$SMUSERNAME" = "yourusername" ]]; then
  USERNAME=""
else
  USERNAME="$SMUSERNAME"
fi

# get the password from $SMPASSWORD. If SMPASSWORD is unset OR yourpassword is the value, set PASSWORD to blank

if [[ -z "$SMPASSWORD" ]] || [[ "$SMPASSWORD" = "yourpassword" ]]; then
  PASSWORD=""
else
  PASSWORD="$SMPASSWORD"
fi

# if either PASSWORD or USERNAME is blank, set SERVER_USER to blank. Otherwise, set SERVER_USER to USERNAME:PASSWORD

if [[ -z "$PASSWORD" ]] || [[ -z "$USERNAME" ]]; then
  SERVER_USER=""
else
  SERVER_USER="$USERNAME:$PASSWORD"
fi

# Input receiver type (dump1090, beast, radarcape_12mhz, radarcape_gps, sbs)
INPUT_TYPE="dump1090"

# Input host:port to connect to for Beast-format messages
INPUT_HOSTPORT="127.0.0.1:30005"

# Multilateration server host:port to provide data to
SERVER_HOSTPORT="127.0.0.1:3333"

# List of result connections/listeners to establish.
# This should be a space-separated list of values suitable for passing to
# # the --results option (see mlat-client --help for syntax)
# RESULTS="beast,connect,127.0.0.1:30004"

# sanitize missing settings
badconfig=""
if [[ -z "$SERVER_USER" ]]; then badconfig+=" SERVER_USER"; fi
if [[ -z "$LAT" ]]; then badconfig+=" LAT"; fi
if [[ -z "$LON" ]]; then badconfig+=" LON"; fi
if [[ -z "$ALT" ]]; then badconfig+=" ALT"; fi
if [[ -z "$INPUT_TYPE" ]]; then INPUT_TYPE=dump1090; fi
if [[ -z "$INPUT_HOSTPORT" ]]; then badconfig+=" INPUT_HOSTPORT"; fi
if [[ -z "$SERVER_HOSTPORT" ]]; then badconfig+=" SERVER_HOSTPORT"; fi

ARGS=()
ARGS+=("--user" "$SERVER_USER")
ARGS+=("--lat" "$LAT")
ARGS+=("--lon" "$LON")
ARGS+=("--alt" "$ALT")
ARGS+=("--input-type" "$INPUT_TYPE")
ARGS+=("--input-connect" "$INPUT_HOSTPORT")
ARGS+=("--server" "$SERVER_HOSTPORT")
ARGS+=("--results" "beast,listen,30105")
ARGS+=("--results" "beast,connect,localhost:30104")
ARGS+=("--stats-json" "/run/mlat-client-stats.json")

if chk_enabled "$MLAT_PRIVACY"; then
    ARGS+=("--privacy")
fi

if [[ -n "$MLAT_RESULTS" ]]; then
    ARGS+=("--results" "$MLAT_RESULTS")
fi

if [[ -n "$badconfig" ]]; then
	"${s6wrap[@]}" echo "Not starting mlat-client-sdrmap, missing configuration options ($badconfig)"
	sleep infinity
fi

if [[ "$SERVER_USER" != *:* ]]; then
	"${s6wrap[@]}" echo "Your credentials seem to be wrong."
	sleep infinity
fi

"${s6wrap[@]}" echo "Starting mlat-client-sdrmap with ${ARGS[*]}"
exec "${s6wrap[@]}" /usr/bin/mlat-client "${ARGS[@]}"
