#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2076

source /scripts/common
mkdir -p /run/readsb

s6wrap=(s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args)

# Build the readsb command line based on options
READSB_BIN="/usr/local/bin/readsb"

READSB_CMD=("--net")
READSB_CMD+=("--quiet")
READSB_CMD+=("--write-json=/run/readsb")
READSB_CMD+=("--net-connector=${BEASTHOST},${BEASTPORT},beast_in")
READSB_CMD+=("--net-bo-port=30005")

if [ -n "${LAT}" ]; then
    READSB_CMD+=(--lat "${LAT}")
fi

if [ -n "${LON}" ]; then
    READSB_CMD+=(--lon "${LON}")
fi

if [[ -n "$READSB_RX_LOCATION_ACCURACY" ]]; then
    READSB_CMD+=("--json-location-accuracy=$READSB_RX_LOCATION_ACCURACY")
fi

if [[ -n "$READSB_JSON_INTERVAL" ]]; then
    READSB_CMD+=("--write-json-every=$READSB_JSON_INTERVAL")
fi

if [ -n "${READSB_DEBUG}" ]; then
    READSB_CMD+=("--debug=$READSB_DEBUG")
fi

# Handle "--max-range=<dist>"
if [[ -n "$READSB_MAX_RANGE" ]]; then
    READSB_CMD+=("--max-range=$READSB_MAX_RANGE")
fi

# shellcheck disable=SC2086
exec "${s6wrap[@]}" "${READSB_BIN}" "${READSB_CMD[@]}" $READSB_EXTRA_ARGS
