#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2076,SC2154

source /scripts/common

if ! chk_enabled "$MLAT"; then
    stop_service
fi

echo "Starting stunnel"
exec "${s6wrap[@]}" stunnel /etc/stunnel/mlat.conf
