#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2154

source /scripts/common

# Define colours
YELLOW='\033[1;33m'
#LIGHTRED='\033[1;31m'
NOCOLOR='\033[0m'

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [[ -z "${BEASTHOST}" ]]; then
  "${s6wrap[@]}" echo -e "${YELLOW}WARNING: No data input configured: BEASTHOST environment variables not set${NOCOLOR}"
  EXITCODE=1
fi
if [[ -z "${LAT}" ]]; then
  "${s6wrap[@]}" echo -e "${YELLOW}WARNING: LAT environment variable not set, Home location will not be accurate${NOCOLOR}"
fi
if [[ -z "${LON}" ]]; then
  "${s6wrap[@]}" echo -e "${YELLOW}WARNING: LON environment variable not set, Home location will not be accurate${NOCOLOR}"
fi
if [[ $EXITCODE -ne 0 ]]; then
  exit 1
fi

# Set up timezone
if [[ -z "${TZ}" ]]; then
  "${s6wrap[@]}" echo -e "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" >/etc/timezone
fi

"${s6wrap[@]}" echo "ADSB feeding      : Enabled"
"${s6wrap[@]}" echo "MLAT feeding      : $(if chk_disabled "$MLAT"; then echo "Disabled"; else echo "Enabled"; fi)"
"${s6wrap[@]}" echo "RadioSonde feeding: $(if compgen -G /opt/radiosonde >/dev/null 2>&1; then echo "Enabled"; else echo "Disabled"; fi)"
"${s6wrap[@]}" echo "Sysinfo feeding   : $(if chk_enabled "$SEND_SYSINFO"; then echo "Enabled"; else echo "Disabled"; fi)"
